

# This file was *autogenerated* from the file warp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_10 = Integer(10)
from civerly.cipher_implementations.warp import WARP_CVL
from civerly.model_options import *
import os
import shutil


model_options = MODEL_OPTIONS(cryptanalysis=CRYPTANALYSIS.DIFFERENTIAL, optimization=OPTIMIZATION.SAT, granularity=GRANULARITY.BITWISE, sbox_modeling=SBOX_MODELING.LOGICAL_COND_ESPRESSO, linear_layer_modeling=LINEAR_LAYER_MODELING.MORE_DUMMIES,logic_minimizer= ESPRESSO_CVL(), path=Path("./temp"), sat_solver=CADICAL_CVL())

for i in range(_sage_const_1 ,_sage_const_10 ):
    warp = WARP_CVL(R=i)
    warp.analyse(model_options)
    warp.generate_report(model_options)
    os.rename("temp/WARP.pdf", f"temp/WARP_diff_{i}.pdf")
    shutil.move(f"temp/WARP_diff_{i}.pdf", f"WARP_diff_{i}.pdf")
    os.system("rm -f temp/*")

