

# This file was *autogenerated* from the file Serpent.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3)
from civerly.cipher_implementations.serpent import SERPENT_CVL
from civerly.model_options import *

serpent = SERPENT_CVL(R=_sage_const_3 )
model_options = MODEL_OPTIONS(cryptanalysis=CRYPTANALYSIS.DIFFERENTIAL, optimization=OPTIMIZATION.SAT, granularity=GRANULARITY.BITWISE, sbox_modeling=SBOX_MODELING.LOGICAL_COND_ESPRESSO, linear_layer_modeling=LINEAR_LAYER_MODELING.MORE_DUMMIES,logic_minimizer= ESPRESSO_CVL(), path=Path("./temp"), sat_solver=CADICAL_CVL())

serpent.analyse(model_options)
serpent.generate_report(model_options)


