

# This file was *autogenerated* from the file Aradi.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_0 = Integer(0)
from civerly.cipher_implementations.aradi import ARADI_CVL
from civerly.model_options import *

aradi = ARADI_CVL(R=_sage_const_4 , rks=[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ])
model_options = model_options = MODEL_OPTIONS(cryptanalysis=CRYPTANALYSIS.DIFFERENTIAL, optimization=OPTIMIZATION.MILP, granularity=GRANULARITY.BITWISE, sbox_modeling=SBOX_MODELING.LOGICAL_COND_ESPRESSO, linear_layer_modeling=LINEAR_LAYER_MODELING.MORE_DUMMIES,logic_minimizer= ESPRESSO_CVL(), path=Path("./temp"), milp_solver=SCIP_CVL())
aradi.model(model_options)
# .mps file is created
#scip = SCIP_CVL()
#scip.invoke(Path("./temp"), Path("./temp")) # timeouts!!!

aradi.analyse(model_options)
aradi.generate_report(model_options)
#results, objective = solver.process_solution_file(output_file)

