

# This file was *autogenerated* from the file Qalqan.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0)
from civerly.cipher_implementations.qalqan import QALQAN_CVL
from civerly.model_options import *

qalqan = QALQAN_CVL(start_round=_sage_const_2 , end_round=_sage_const_2 , key=_sage_const_0 )
model_options = MODEL_OPTIONS(cryptanalysis=CRYPTANALYSIS.DIFFERENTIAL, optimization=OPTIMIZATION.MILP, granularity=GRANULARITY.BITWISE, sbox_modeling=SBOX_MODELING.LOGICAL_COND_ESPRESSO, linear_layer_modeling=LINEAR_LAYER_MODELING.MORE_DUMMIES, logic_minimizer= ESPRESSO_CVL(), path=Path("./temp"), milp_solver=SCIP_CVL())

qalqan.analyse(model_options)
qalqan.generate_report(model_options)

